### ISSUE TITLE
Valid installation of TensorFlow not found

### ISSUE THREAD

**Issue by metalichen** [ruthkr/deepredeff#5]
Hi there!

I was trying to install deepredeff on my macbook, and ran into a problem with tensorflow. When I run install_tensorflow(), it finishes without error. It does give me several warnings, maybe they are relevant here:
```
WARNING conda.core.path_actions:verify(1051): Unable to create environments file. Path not writable.
  environment location: /Users/gol22pin/.conda/environments.txt
WARNING conda.core.envs_manager:register_env(52): Unable to register environment. Path not writable or missing.
  environment location: /Users/gol22pin/Library/r-miniconda/envs/r-tensorflow
  registry file: /Users/gol22pin/.conda/environments.txt
```

If after that I try running predict_effector(), I get the following:
```
Error: Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/bin/python3.11

Python exception encountered:
Traceback (most recent call last):
File "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
return _run_hook(name, _hook)
^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
module = hook()
^^^^^^
File "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
return _find_and_load(name, import_)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tensorflow'


You can install TensorFlow using the install_tensorflow() function.
```

It looks like it's looking for tensorflow in the wrong place? Any advice on getting tensorflow to work would be greatly apprecieated!

Here is my session info:
```
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 13.3.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
 [1] ggVennDiagram_1.2.3 phylotools_0.2.2    phytools_1.9-16    
 [4] maps_3.4.1          ape_5.7-1           deepredeff_0.1.1   
 [7] Biostrings_2.62.0   GenomeInfoDb_1.30.1 XVector_0.34.0     
[10] IRanges_2.28.0      S4Vectors_0.32.4    BiocGenerics_0.40.0
[13] BiocManager_1.30.22 lubridate_1.9.2     forcats_1.0.0      
[16] stringr_1.5.0       dplyr_1.1.3         purrr_1.0.2        
[19] readr_2.1.4         tidyr_1.3.0         tibble_3.2.1       
[22] ggplot2_3.4.3       tidyverse_2.0.0    

loaded via a namespace (and not attached):
 [1] jsonlite_1.8.7          foreach_1.5.2          
 [3] expm_0.999-7            GenomeInfoDbData_1.2.7 
 [5] numDeriv_2016.8-1.1     pillar_1.9.0           
 [7] lattice_0.21-8          quadprog_1.5-8         
 [9] glue_1.6.2              reticulate_1.32.0      
[11] phangorn_2.11.1         digest_0.6.33          
[13] RVenn_1.1.0             colorspace_2.1-0       
[15] htmltools_0.5.6         Matrix_1.6-1           
[17] pkgconfig_2.0.3         zlibbioc_1.40.0        
[19] scales_1.2.1            whisker_0.4.1          
[21] tzdb_0.4.0              optimParallel_1.0-2    
[23] timechange_0.2.0        combinat_0.0-8         
[25] generics_0.1.3          keras_2.13.0           
[27] withr_2.5.0             cli_3.6.1              
[29] mnormt_2.1.1            magrittr_2.0.3         
[31] crayon_1.5.2            fansi_1.0.4            
[33] doParallel_1.0.17       nlme_3.1-163           
[35] MASS_7.3-60             tools_4.1.2            
[37] hms_1.1.3               lifecycle_1.0.3        
[39] munsell_0.5.0           plotrix_3.8-2          
[41] compiler_4.1.2          clusterGeneration_1.3.8
[43] rlang_1.1.1             grid_4.1.2             
[45] RCurl_1.98-1.12         iterators_1.0.14       
[47] rstudioapi_0.15.0       htmlwidgets_1.6.2      
[49] igraph_1.5.1            base64enc_0.1-3        
[51] bitops_1.0-7            gtable_0.3.4           
[53] codetools_0.2-19        R6_2.5.1               
[55] tfruns_1.5.1            tensorflow_2.13.0      
[57] knitr_1.44              zeallot_0.1.0          
[59] fastmap_1.1.1           utf8_1.2.3             
[61] fastmatch_1.1-4         stringi_1.7.12         
[63] parallel_4.1.2          Rcpp_1.0.11            
[65] vctrs_0.6.3             png_0.1-8              
[67] scatterplot3d_0.3-44    tidyselect_1.2.0       
[69] xfun_0.40               coda_0.19-4            
```

Thanks!
Gulnara

**Comment by ruthkr** [comment]
Hi @metalichen 😊 
Thank you for installing {deepredeff} and reporting this issue.

I've made some changes to the `install_tensorflow()` function to give support for Apple Silicon (M1 and M2) machines.
I'm still in the process of finishing some other updates and submitting to CRAN, but in the meantime you can install the development version of {deepredeff} by running the following:
```r
devtools::install_github("ruthkr/deepredeff")
```

After it's updated, you should be able to install TensorFlow with no issues:
```r
library(deepredeff)
install_tensorflow()
```

Thanks,
Ruth

**Comment by metalichen** [comment]
Thank you, it worked!
